<?xml version="1.0"?>
<robot name="cracker_box" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="length" value="0.16" />
  <xacro:property name="width" value="0.06" />
  <xacro:property name="height" value="0.21" />
  <xacro:property name="M" value="0.3" />


  <link name="cracker_box_base_link"/>

  <link name="cracker_box_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${M}"/>
      <inertia ixx="${1/12*M*(length**2+width**2)}"  ixy="0"  ixz="0" iyy="${1/12*M*(length**2+height**2)}" iyz="0" izz="${1/12*M*(width**2+height**2)}" />
    </inertial>

    <visual>
      <geometry>
        <box size="${length} ${width} ${height}" />
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>

   <collision>
     <origin xyz="0 0 0" rpy="0 0 0"/>
     <geometry>
       <box size="${length} ${width} ${height}" />
     </geometry>
   </collision>
  </link>

  <joint name="base_to_box" type="fixed">
   <parent link="cracker_box_base_link" />
   <child link="cracker_box_link" />
   <origin xyz="0 0 ${height/2.0}" rpy="0 0 0" />
  </joint>

  <gazebo reference="cracker_box_link">
    <material>Gazebo/Red</material>
  </gazebo>

</robot>
